# Generated by Django 4.1.7 on 2024-02-02 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
