# Generated by Django 4.1.7 on 2023-03-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_comment_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
